language: lua

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luacov-coveralls
  - luarocks install busted

install:
  - luarocks make

script:
  - busted -c

after_success:
  - luacov
  - luacov-coveralls -v
